### ISSUE TITLE
Zero values are being sent which may not be desired

### ISSUE THREAD

**Issue by leonardochaia** [monero-ecosystem/go-monero-rpc-client#4]
Take the below example:

```go
package main

import (
	"testing"

	"github.com/leonardochaia/go-monero-rpc-client/wallet"
)

func TestTX(t *testing.T) {
	// Start a wallet client instance
	client := wallet.New(wallet.Config{
		Address: "http://127.0.0.1:18082/json_rpc",
	})
	// get incoming transfers
	resp1, err := client.GetTransfers(&wallet.RequestGetTransfers{
		In:             true,
		FilterByHeight: true,
		MinHeight:      4200,
		// MaxHeight:      21492184123,
	})

	if err != nil {
		t.Fatal(err)
	}

	if len(resp1.In) == 0 {
		t.Log("Expected incoming transfers, got zero")
		t.FailNow()
	}
}
```
Given that no value is provided for `MaxHeight`, 0 is being sent, which makes `monero-wallet-rpc` filter by height < maxHeight which returns no results.

If you provide a huge `MaxHeight` like the commented line, or if you add `omitempty` to the struct it works properly.

I propose we add `omitempty` to all structs that represent incoming parameters, i.e:

```go

type RequestGetTransfers struct {
	// [redacted]
	FilterByHeight bool `json:"filter_by_height,omitempty"`
	// (Optional) Minimum block height to scan for transfers, if filtering by height is enabled.
	MinHeight uint64 `json:"min_height,omitempty"`
	// (Opional) Maximum block height to scan for transfers, if filtering by height is enabled (defaults to max block height).
	MaxHeight uint64 `json:"max_height,omitempty"`
}
```

What do you guys think? I don't see other workaround other than modifying the library.

**Comment by leonardochaia** [comment]
Hi @omani @rbrunner7 hope you're doing well.

I'm willing to throw a PR to "fix" this, but I'd appreciate some guidance on how you want it fixed, perhaps there's something I'm not seeing.

Thank you.

**Comment by omani** [comment]
hi @leonardochaia,
thanks for your proposal for the fix. it would solve the issue. a step further and better option would be to compare and `omitempty` every field that is declared as `KV_SERIALIZE_OPT` (read: optional) in https://github.com/monero-project/monero/blob/master/src/wallet/wallet_rpc_server_commands_defs.h

if you want, you can provide a complete PR for this. otherwise feel free to submit the PR for your case and I will complete it afterwards.

**Comment by leonardochaia** [comment]
I'm willing to do it where it's needed, no problem.
I'll search for each field in the file you've linked and add `omitempty` on the struct.

Something to bear in mind is that this might introduce breaking changes tho.

**Comment by omani** [comment]
we will see. if you have to change a field to a pointer in the struct, that might be the case. (changing the way we treat default data type values and `nil`).

 in any case, once we get your PR we can check for breaking changes and discuss this in the review process.

**Comment by leonardochaia** [comment]
Hmmm OK. I'm hoping I don't have to change field types, but I think it'll most likely depend on whether we need to send zero values or not. In my original issue, it's clear that `max_height: 0` does not make sense, but perhaps there are cases when `*uint64` is needed instead, to be able to send `0`.

When I mentioned breaking changes I was thinking on the fact that some clients may be relying on the default values being sent, and with `omitempty` this behavior will change silently.

**Comment by omani** [comment]
>When I mentioned breaking changes I was thinking on the fact that some clients may be relying on the default values being sent, and with omitempty this behavior will change silently.

I doubt that - at least hope so - since the API itself makes it explicitly optional. treating MaxHeight with default 0 would be wrong in the first place (according to the API).
